name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version and publish to npm
        uses: bcomnes/npm-bump@v2
        with:
          git_email: pouya.saadeghi@gmail.com
          git_username: ${{ github.actor }}
          newversion: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.npm_token }}
