name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

#       - name: publish to npm
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: version & publish
        uses: geeman201/conventional-changelog-npm-publish/@v14
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
