name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#       - name: publish to npm
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - uses: neg4n/version-bump@main
        with:
          git-user-email: 'pouya.saadeghi@gmail.com'    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
