name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#       - name: publish to npm
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - uses: copapow/version-bump-package@v1
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # required
